"""Provider-neutral source control contracts, errors, and registry."""

from forge.integrations.source_control.contracts import (
    Actor,
    ChangeRequest,
    ChangeRequestIdentity,
    ChangeRequestState,
    CheckConclusion,
    CheckRun,
    CheckStatus,
    Connection,
    EventKind,
    NormalizedEvent,
    Provider,
    RepositoryRef,
    RepositoryResolver,
    ResolvedRepository,
    Review,
    ReviewComment,
    ReviewState,
    SourceControlProvider,
    WriteTarget,
)
from forge.integrations.source_control.errors import (
    AuthenticationError,
    ConflictError,
    NotFoundError,
    ProviderConfigError,
    RateLimitedError,
    SourceControlError,
    TransientProviderError,
)
from forge.integrations.source_control.registry import (
    Registry,
    get_registry,
    load_registry,
    register_adapter_factory,
)

__all__ = [
    "Actor",
    "AuthenticationError",
    "ChangeRequest",
    "ChangeRequestIdentity",
    "ChangeRequestState",
    "CheckConclusion",
    "CheckRun",
    "CheckStatus",
    "ConflictError",
    "Connection",
    "EventKind",
    "NormalizedEvent",
    "NotFoundError",
    "Provider",
    "ProviderConfigError",
    "RateLimitedError",
    "Registry",
    "RepositoryRef",
    "RepositoryResolver",
    "ResolvedRepository",
    "Review",
    "ReviewComment",
    "ReviewState",
    "SourceControlError",
    "SourceControlProvider",
    "TransientProviderError",
    "WriteTarget",
    "get_registry",
    "load_registry",
    "register_adapter_factory",
]
