apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.serviceAccountName }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sandbox.jobServiceAccountName }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
