apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workspace.claimName }}
  {{- if .Values.workspace.retain }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  {{- with .Values.workspace.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
